In [ ]:
import numpy as np
#creating arrays
arr = np.array([1,2,3,4,5])
print(arr)

[1 2 3 4 5]


In [ ]:
zeros_ajju = np.zeros((3,3), dtype=float)
print(zeros_ajju)
ones_ajju=np.ones((2,2), dtype=int)
print(ones_ajju)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]
[[1 1]
 [1 1]]


In [ ]:
ones_ajju=np.ones ((3,3), dtype=int)
print(ones_ajju)
arange_arr=np.arange(10)
print(arange_arr)
reshaped_arr=arr.reshape(5,1)
print(reshaped_arr)
sliced_arr=arr[2:4]
print(sliced_arr)
a=np.array([1,2,3,4,5,6,7,8])
b= a.T
print(b)
b=np.split(a,4)
print(b)

[[1 1 1]
 [1 1 1]
 [1 1 1]]
[0 1 2 3 4 5 6 7 8 9]
[[1]
 [2]
 [3]
 [4]
 [5]]
[3 4]
[1 2 3 4 5 6 7 8]
[array([1, 2]), array([3, 4]), array([5, 6]), array([7, 8])]


In [ ]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
c=np.dot(a,b)
print(c)
d=np.linalg.eig(c)
print(d)


[[19 22]
 [43 50]]
EigResult(eigenvalues=array([5.80198014e-02, 6.89419802e+01]), eigenvectors=array([[-0.75781077, -0.40313049],
       [ 0.65247439, -0.91514251]]))


In [25]:
a=np.array([[1,2],[3,4]])
print(type(a))
b=np.linspace(1.4,2,5)
print(b)


<class 'numpy.ndarray'>
[1.4  1.55 1.7  1.85 2.  ]


In [ ]:
import numpy as np
data= np.loadtxt("/content/drive/MyDrive/dataset/1st day.txt",dtype=int)
d=np.savetxt("/content/date.txt",data)
print(d)
print(data)

None
[        2920936245               2863              98679
 479397967978892572      8763967965756   8796543524124345]


In [12]:
arange_arr=np.arange(0,1000,5)

print(arange_arr)
d=np.savetxt("/content/date.txt", arange_arr)
data= np.loadtxt("/content/date.txt",dtype=int)
arange_arr=np.random.rand()
np.random.rand(int)
print(arange_arr)

[  0   5  10  15  20  25  30  35  40  45  50  55  60  65  70  75  80  85
  90  95 100 105 110 115 120 125 130 135 140 145 150 155 160 165 170 175
 180 185 190 195 200 205 210 215 220 225 230 235 240 245 250 255 260 265
 270 275 280 285 290 295 300 305 310 315 320 325 330 335 340 345 350 355
 360 365 370 375 380 385 390 395 400 405 410 415 420 425 430 435 440 445
 450 455 460 465 470 475 480 485 490 495 500 505 510 515 520 525 530 535
 540 545 550 555 560 565 570 575 580 585 590 595 600 605 610 615 620 625
 630 635 640 645 650 655 660 665 670 675 680 685 690 695 700 705 710 715
 720 725 730 735 740 745 750 755 760 765 770 775 780 785 790 795 800 805
 810 815 820 825 830 835 840 845 850 855 860 865 870 875 880 885 890 895
 900 905 910 915 920 925 930 935 940 945 950 955 960 965 970 975 980 985
 990 995]


<ipython-input-12-3974ab74f250>:5: DeprecationWarning: loadtxt(): Parsing an integer via a float is deprecated.  To avoid this warning, you can:
    * make sure the original data is stored as integers.
    * use the `converters=` keyword argument.  If you only use
      NumPy 1.23 or later, `converters=float` will normally work.
    * Use `np.loadtxt(...).astype(np.int64)` parsing the file as
      floating point and then convert it.  (On all NumPy versions.)
  (Deprecated NumPy 1.23)
  data= np.loadtxt("/content/date.txt",dtype=int)


TypeError: 'type' object cannot be interpreted as an integer

In [19]:
a=np.random.rand()
print(a)
b=np.random.randint(2,10)
print(b)

0.38021826525013747
5


In [39]:
a=np.arange(25).reshape(4,5,1)
print(a)

ValueError: cannot reshape array of size 25 into shape (4,5,1)

In [43]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(a/b)
print(a-b)
c=np.dot(a,b)
print(c)

[[0.2        0.33333333]
 [0.42857143 0.5       ]]
[[-4 -4]
 [-4 -4]]
[[19 22]
 [43 50]]


In [53]:
from numpy import random
a=np.ones((2,3),dtype=int)
print(a.sum(axis=0))

[2 2 2]


In [66]:
a=np.ceil(np.random.random((2,2)))
c=np.ceil(np.random.random((2,2)))
print(a)
print(c)

[[1. 1.]
 [1. 1.]]
[[1. 1.]
 [1. 1.]]


In [73]:
from numpy import random
a=np.ones((2,2),dtype=int)
print(a.cumsum(axis=0))

[[1 1]
 [2 2]]


In [77]:
a = np.array([2,3,5,6])
print(np.cumsum(a))

[ 2  5 10 16]


In [85]:
a = np.array([1,2,3,4,5,6])
a.resize(3,2)
print(a.shape)

print(a)

(3, 2)
[[1 2]
 [3 4]
 [5 6]]


In [94]:
a = np.array([1,2,3,4,5,6])
a.resize(2,3)
b = np.array([11,12,13,14,15,16])
b.resize(2,3)
print(np.vstack((a,b)))
print(np.hstack((a,b)))

[[ 1  2  3]
 [ 4  5  6]
 [11 12 13]
 [14 15 16]]
[[ 1  2  3 11 12 13]
 [ 4  5  6 14 15 16]]


number of rows become number of group
column becomes rows
group become column


In [5]:
import numpy as np
a1=np.eye(4)
print(a1)
a2=np.full((2,2),3)
print(a2)
x=[1,2,3]
a=np.asarray(x)
print(a)
print(type(a))

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]
[[3 3]
 [3 3]]
[1 2 3]
<class 'numpy.ndarray'>


In [6]:
x=np.array([1,4,0],float)
y=np.array([2,2,1],float)
print(np.inner(x,y))
print(np.outer(x,y))
print(np.cross(x,y))

10.0
[[2. 2. 1.]
 [8. 8. 4.]
 [0. 0. 0.]]
[ 4. -1. -6.]


inner means multiplication of elements column wise(or) group wise
outer means multiplication of one element to all other elements in another array
cross product means leaving that row and appling cross mul

In [8]:
a=np.array([1.1,2.2,3.3,4.4,5.5,6.6,7.7])

b=np.rint(a)
print(b)

[1. 2. 3. 4. 6. 7. 8.]


In [15]:
a=np.array([3,2,3,4])
b=np.array([5,6,4,8])
print(np.true_divide(a,b))

[0.6        0.33333333 0.75       0.5       ]


In [10]:
a=np.array([1,2,2,2,3,4,5])
print(np.unique(a))

[1 2 3 4 5]


In [14]:
a=np.array([[3,2],[3,4]])
b=np.array([[5,6],[7,8]])
print(np.union1d(a,b))

[2 3 4 5 6 7 8]


In [18]:
a=np.array([[3,2],[3,4]])
b=np.array([[3,6],[3,8]])
print(np.intersect1d(a,b))

[3]


In [21]:
a=np.array([[1,2],[3,4]])
b=np.array([[5,2],[7,4]])
print(np.setdiff1d(a,b))

[1 3]


In [25]:
a=8
b=6
c=np.hypot(a,b)
print(c)
x=np.sin(180)
print(x)

10.0
-0.8011526357338304


In [33]:
a=np.array([10,21,30,40,50,60])
b=np.array([20,21,2,20,25,25])
c=np.divmod(a,b)
print(c)
c=np.mod(a,b)
print(d)
e=np.divide(a,b)
print(e)
f=np.multiply(a,b)
print(f)
g=np.matmul(a,b)
print(g)

(array([ 0,  1, 15,  2,  2,  2]), array([10,  0,  0,  0,  0, 10]))
[10  0  0  0  0 10]
[ 0.5  1.  15.   2.   2.   2.4]
[ 200  441   60  800 1250 1500]
4251


In [35]:
from numpy import random
x=random.normal(size=(2,3))
print(x)
i=random.normal(loc=1,scale=2,size=(2,3))
print(i)

[[-0.2394376  -0.02822691 -0.68908188]
 [-0.31303897 -0.91808554  0.18746524]]
[[-0.80928223 -2.67396707  3.6542416 ]
 [ 1.01704469  2.31231001 -0.85463956]]


loc denotes mean value
scale denotes standard deviation


.normal is defines as guassian distribution

In [36]:
x=random.binomial(n=12,p=0.5,size=10)
print(x)

[9 5 4 7 7 7 3 3 4 8]


In [42]:
x=random.poisson(lam=2,size=10)
print(x)
y=random.choice([1,2,3,4])
print(y)
z=random.choice([3,5],p=[0.5,0.5],size=(3,5))
print(z)

[3 1 4 3 2 1 2 3 3 3]
1
[[3 5 5 3 5]
 [3 5 5 5 5]
 [5 5 3 5 5]]
